"""empty message

Revision ID: 14c919d51370
Revises: 
Create Date: 2018-01-16 18:54:38.054108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c919d51370'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minified_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=155), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minified_url')
    # ### end Alembic commands ###
